"""Shared CLI registration for config-backed section.key overrides."""

from grid_cells.common.config import str2bool


CONFIG_OVERRIDE_SPECS = {
    "task": {
        "env_size": {"type": float},
        "n_pc": {"type": int, "nargs": "+"},
        "pc_scale": {"type": float, "nargs": "+"},
        "n_hdc": {"type": int, "nargs": "+"},
        "hdc_concentration": {"type": float, "nargs": "+"},
        "seq_len": {"type": int},
        "cells_path": {"type": str},
        "neurons_seed": {"type": int},
        "targets_type": {"type": str},
        "lstm_init_type": {"type": str},
        "decode_type": {"type": str},
        "velocity_noise": {"type": float, "nargs": "+"},
        "motion_dt": {"type": float},
        "motion_b":  {"type": float},
        "motion_mv": {"type": float},
        "motion_sv": {"type": float},
        "motion_mw": {"type": float},
        "motion_sw": {"type": float},
    },
    "model": {
        "nh_lstm": {"type": int},
        "nh_bottleneck": {"type": int},
        "dropout_rate": {"type": float},
        "bottleneck_has_bias": {"type": str2bool},
        "init_weight_disp": {"type": float},
    },
    "training": {
        "epochs": {"type": int},
        "steps_per_epoch": {"type": int},
        "batch_size": {"type": int},
        "datadir": {"type": str},
        "data_path": {"type": str},
        "eval_num_samples": {"type": int},
        "eval_data_path": {"type": str},
        "optimizer": {"type": str},
        "lr": {"type": float},
        "lr_scheduler": {"type": str},
        "lr_min": {"type": float},
        "lr_step_size": {"type": int},
        "lr_gamma": {"type": float},
        "momentum": {"type": float},
        "adamw_betas": {"type": float, "nargs": 2},
        "adamw_eps": {"type": float},
        "weight_decay": {"type": float},
        "grad_clip": {"type": float},
        "grad_clip_mode": {"type": str},
        "grad_clip_scope": {"type": str},
        "grad_clip_norm_type": {"type": str},
        "first_pos_loss_multiplier": {"type": float},
        "eval_every": {"type": int},
        "num_workers": {"type": int},
        "save_dir": {"type": str},
        "run_name": {"type": str},
        "timestamp_save_dir": {"type": str2bool},
        "checkpoint_every": {"type": int},
        "save_final_checkpoint": {"type": str2bool},
        "use_tqdm": {"type": str2bool},
        "use_tensorboard": {"type": str2bool},
        "tensorboard_log_every": {"type": int},
        "eval_loader_batch_size": {"type": int},
        "eval_plot_every": {"type": int},
        "eval_num_workers": {"type": int},
        "eval_chunk_size": {"type": int},
        "eval_units_per_page": {"type": int},
        "eval_pdf_dpi": {"type": int},
    },
    "visualization": {
        "spatial_bins": {"type": int},
        "directional_bins": {"type": int},
        "anim_num_traj": {"type": int},
        "anim_fps": {"type": int},
        "anim_step": {"type": int},
        "anim_workers": {"type": int},
    },
    "analysis": {
        "enabled": {"type": str2bool},
        "compute_grid_selectivity": {"type": str2bool},
        "compute_grid_geometry": {"type": str2bool},
        "compute_shuffle_significance": {"type": str2bool},
        "compute_split_half": {"type": str2bool},
        "compute_hd_selectivity": {"type": str2bool},
        "compute_linear_spatial_pca": {"type": str2bool},
        "num_shuffles": {"type": int},
        "linear_spatial_pca_top_k": {"type": int},
        "linear_spatial_pca_fit_fraction": {"type": float},
        "linear_spatial_pca_num_shuffles": {"type": int},
        "linear_spatial_pca_save_plots": {"type": str2bool},
        "linear_spatial_pca_plot_top_n": {"type": int},
        "scale_discreteness_num_shuffles": {"type": int},
        "scale_discreteness_bins": {"type": int},
        "scale_discreteness_min_bins": {"type": float},
        "scale_discreteness_max_bins": {"type": float},
        "scale_gmm_max_components": {"type": int},
        "gridness_threshold": {"type": float},
        "fdr_alpha": {"type": float},
        "min_shift_fraction": {"type": float},
        "split_half_min_corr": {"type": float},
        "max_eval_trajectories": {"type": int},
        "random_seed": {"type": int},
    },
    "data_generation": {
        "num_samples": {"type": int},
        "eval_num_samples": {"type": int},
        "num_workers": {"type": int},
        "progress_every": {"type": int},
        "vis_output": {"type": str},
        "anim_output": {"type": str},
        "progress_output": {"type": str},
        "eval_progress_output": {"type": str},
    },
}


def register_config_overrides(parser, sections=None):
    """Attach shared --section.key override arguments to a parser."""
    for section, fields in CONFIG_OVERRIDE_SPECS.items():
        if sections is not None and section not in sections:
            continue
        for field, spec in fields.items():
            parser.add_argument(
                f"--{section}.{field}",
                dest=f"{section}__{field}",
                default=None,
                **spec,
            )
    return parser
